import { useCallback, useEffect, useMemo, useState } from 'react';
import { ParsedCsvRow } from '../lib/csv';

type Status = 'pending' | 'processing' | 'posted' | 'failed' | 'blocked' | 'uncertain' | 'skipped';
interface Job { id: string; groupName: string; groupUrl: string; postText: string; status: Status; attempts: number; lastError: string | null; }
interface WorkerStatus { state: string; currentJob: Job | null; currentStep: string; lastError: string | null; browser: { profileExists: boolean; open: boolean; headless: boolean }; }
const blankStatus: WorkerStatus = { state: 'offline', currentJob: null, currentStep: 'Backend unavailable', lastError: null, browser: { profileExists: false, open: false, headless: false } };

export function AutomationDashboard({ rows }: { rows: ParsedCsvRow[] }) {
  const [jobs, setJobs] = useState<Job[]>([]); const [status, setStatus] = useState(blankStatus); const [error, setError] = useState('');
  const [settings, setSettings] = useState({ delayMs: 15000, cooldownMs: 0, maxJobs: 10, stopOnFailure: false, stopOnCheckpoint: true, headless: false });
  const refresh = useCallback(async () => { try { const [queue, state] = await Promise.all([api('/api/queue'), api('/api/status')]); setJobs(queue); setStatus(state); setError(''); } catch { setError('Automatic posting backend is offline. Start it with python app.py.'); } }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 2000); return () => window.clearInterval(timer); }, [refresh]);
  const counts = useMemo(() => Object.fromEntries(['pending', 'processing', 'posted', 'failed', 'blocked', 'uncertain'].map((key) => [key, jobs.filter((job) => job.status === key).length])), [jobs]);
  const command = async (path: string, body: unknown = {}) => { try { await api(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await refresh(); } catch (e) { setError((e as Error).message); } };
  const queueRows = () => command('/api/queue/import', { rows: rows.map((row) => ({ groupName: row.name, groupUrl: row.url, postText: row.ad })) });
  return <section className="mx-auto w-full max-w-6xl space-y-4 rounded-3xl border border-violet-500/30 bg-slate-950/80 p-5 shadow-xl">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-300">Playwright automation</p><h1 className="text-3xl font-semibold">Posting queue</h1><p className="text-sm text-slate-400">Browser: {status.browser.open ? 'open' : status.browser.profileExists ? 'profile saved' : 'not created'} · Mode: {settings.headless ? 'headless' : 'visible'} · Worker: {status.state}</p></div><div className="flex flex-wrap gap-2"><Button label="Queue Manual CSV" onClick={queueRows} disabled={!rows.length}/><Button label="Open Visible Browser / Login" onClick={() => command('/api/browser/login', { headless: settings.headless })} disabled={settings.headless}/></div></div>
    {error && <p className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100">{error}</p>}
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><Metric label="Total" value={jobs.length}/>{Object.entries(counts).map(([key, value]) => <Metric key={key} label={key} value={value}/>)}</div>
    <div className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:grid-cols-3"><Field label="Delay between jobs (seconds)" value={settings.delayMs / 1000} onChange={(value) => setSettings({ ...settings, delayMs: value * 1000 })}/><Field label="Cooldown (seconds)" value={settings.cooldownMs / 1000} onChange={(value) => setSettings({ ...settings, cooldownMs: value * 1000 })}/><Field label="Maximum jobs" value={settings.maxJobs} onChange={(value) => setSettings({ ...settings, maxJobs: value })}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.stopOnFailure} onChange={(event) => setSettings({ ...settings, stopOnFailure: event.target.checked })}/> Stop on failure</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.stopOnCheckpoint} onChange={(event) => setSettings({ ...settings, stopOnCheckpoint: event.target.checked })}/> Stop on security checkpoint</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.headless} disabled={status.browser.open} onChange={(event) => setSettings({ ...settings, headless: event.target.checked })}/> Run browser headless</label></div>
    <p className="text-xs text-slate-400">Headless mode runs without a visible browser window. Use visible mode for the first Facebook login and checkpoints; close an open Playwright browser before switching modes.</p>
    <div className="flex flex-wrap gap-2"><Button label="Start" onClick={() => command('/api/queue/start', settings)}/><Button label="Pause" onClick={() => command('/api/queue/pause')}/><Button label="Resume" onClick={() => command('/api/queue/resume')}/><Button label="Stop" onClick={() => command('/api/queue/stop')}/><Button label="Clear Automation Queue" onClick={() => command('/api/queue/clear')} disabled={!jobs.length}/></div>
    <div className="rounded-2xl border-2 border-violet-400/60 bg-gradient-to-r from-violet-950/70 via-slate-900/80 to-slate-950 p-5 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-bold uppercase tracking-widest text-violet-100">Current job</h2><Button label="Skip Current & Continue" onClick={() => command('/api/queue/current/skip')} disabled={!status.currentJob || status.state !== 'running'}/></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Current Group" value={status.currentJob?.groupName || 'None'}/><Info label="Current Status" value={status.currentJob?.status || status.state}/><Info label="Current Step" value={status.currentStep}/><Info label="Last Error" value={status.lastError || 'None'}/></dl></div>
    <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="p-2">Group</th><th className="p-2">Post preview</th><th className="p-2">Status</th><th className="p-2">Attempts</th><th className="p-2">Last error</th><th className="p-2">Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-t border-slate-800"><td className="p-2 font-medium">{job.groupName}</td><td className="max-w-xs truncate p-2">{job.postText}</td><td className="p-2">{job.status}</td><td className="p-2">{job.attempts}</td><td className="max-w-xs truncate p-2 text-rose-300" title={job.lastError || ''}>{job.lastError || '—'}</td><td className="p-2"><div className="flex gap-2"><a href={job.groupUrl} target="_blank" rel="noreferrer">Open Group</a>{['failed','blocked','uncertain','skipped'].includes(job.status) && <button className="text-sky-300" onClick={() => command(`/api/queue/${job.id}/retry`)}>Retry</button>}{!['posted','skipped'].includes(job.status) && <button className="text-amber-300" onClick={() => command(`/api/queue/${job.id}/skip`)}>Skip</button>}</div></td></tr>)}</tbody></table>{!jobs.length && <p className="p-4 text-sm text-slate-400">Queue rows from the manual window to begin.</p>}</div>
  </section>;
}
async function api(path: string, init?: RequestInit) { const response = await fetch(path, init); const data = await response.json(); if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); return data; }
function Button({ label, onClick, disabled }: { label: string; onClick: () => void; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className="min-h-11 rounded-full border border-violet-400/50 bg-violet-500/20 px-4 text-sm font-semibold text-violet-50 disabled:cursor-not-allowed disabled:opacity-40">{label}</button>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-900 p-3"><p className="text-xs capitalize text-slate-400">{label}</p><p className="text-xl font-bold">{value}</p></div>; }
function Field({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-slate-400">{label}<input type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-white"/></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-700 bg-slate-950/60 p-3"><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 font-semibold text-white">{value}</dd></div>; }
