import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ParsedCsvRow } from '../lib/csv';

type Status = 'pending' | 'processing' | 'posted' | 'failed' | 'blocked' | 'uncertain' | 'skipped';
interface Job { id: string; groupName: string; groupUrl: string; postText: string; status: Status; attempts: number; lastError: string | null; }
interface WorkerStatus { hosted?: boolean; logs?: { id: number; time: string; message: string; group: string | null }[]; state: string; currentJob: Job | null; currentStep: string; lastError: string | null; browser: { profileExists: boolean; open: boolean; headless: boolean }; }
const blankStatus: WorkerStatus = { state: 'offline', currentJob: null, currentStep: 'Backend unavailable', lastError: null, browser: { profileExists: false, open: false, headless: false } };

export function AutomationDashboard({ rows }: { rows: ParsedCsvRow[] }) {
  const [jobs, setJobs] = useState<Job[]>([]); const [status, setStatus] = useState(blankStatus); const [error, setError] = useState('');
  const [settings, setSettings] = useState({ delayMs: 15000, cooldownMs: 0, maxJobs: 10, stopOnFailure: false, stopOnCheckpoint: true, headless: false, joinBeforePost: false, composerTimeoutMs: 15000, acceptGroupRules: true, copyClipboard: false });
  const [membershipText, setMembershipText] = useState(() => localStorage.getItem('pastehappy-membership-answers') ?? 'agree = I agree\nrules = I agree\naccept = I agree');
  useEffect(() => { localStorage.setItem('pastehappy-membership-answers', membershipText); }, [membershipText]);
  const startRun = () => {
    const lines = membershipText.split('\n').map(line => line.trim()).filter(Boolean);
    if (lines.some(line => line.indexOf('=') < 1 || !line.slice(line.indexOf('=') + 1).trim())) { setError('Use one question phrase = answer per line.'); return; }
    const membershipAnswers = lines.map(line => ({ question: line.slice(0, line.indexOf('=')).trim(), answer: line.slice(line.indexOf('=') + 1).trim() }));
    command('/api/queue/start', { ...settings, membershipAnswers });
  };
  const csvInputRef = useRef<HTMLInputElement>(null);
  const [importing, setImporting] = useState(false);
  const importCsv = async (file: File) => {
    setImporting(true);
    try {
      const csv = await file.text();
      await api('/api/queue/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ csv }) });
      await refresh();
    } catch (e) { setError((e as Error).message); }
    finally { setImporting(false); }
  };
  const initializedMode = useRef(false);
  const refresh = useCallback(async () => { try { const [queue, state] = await Promise.all([api('/api/queue'), api('/api/status')]); setJobs(queue); setStatus(state); if (!initializedMode.current) { setSettings(current => ({ ...current, headless: state.browser.headless })); initializedMode.current = true; } setError(''); } catch { setError('Automatic posting backend is offline. Start it with python app.py.'); } }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 2000); return () => window.clearInterval(timer); }, [refresh]);
  const counts = useMemo(() => Object.fromEntries(['pending', 'processing', 'posted', 'failed', 'blocked', 'uncertain', 'skipped'].map((key) => [key, jobs.filter((job) => job.status === key).length])), [jobs]);
  const command = async (path: string, body: unknown = {}) => { try { await api(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await refresh(); } catch (e) { setError((e as Error).message); } };
  const queueRows = () => command('/api/queue/import', { rows: rows.map((row) => ({ groupName: row.name, groupUrl: row.url, postText: row.ad })) });
  return <section className="mx-auto w-full max-w-6xl space-y-4 rounded-3xl border border-violet-500/30 bg-slate-950/80 p-5 shadow-xl">
    <div className="rounded-2xl border-2 border-violet-400/60 bg-gradient-to-r from-violet-950/70 via-slate-900/80 to-slate-950 p-5 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-bold uppercase tracking-widest text-violet-100">Current job</h2><Button label="Skip Current & Continue" onClick={() => command('/api/queue/current/skip')} disabled={!status.currentJob || status.state !== 'running'}/></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Current Group" value={status.currentJob?.groupName || 'None'}/><Info label="Current Status" value={status.currentJob?.status || status.state}/><Info label="Current Step" value={status.currentStep}/><Info label="Last Error" value={status.lastError || 'None'}/></dl></div>
    <div className="flex flex-wrap gap-2"><Button label="Start" onClick={startRun}/><Button label="Pause" onClick={() => command('/api/queue/pause')}/><Button label="Resume" onClick={() => command('/api/queue/resume')}/><Button label="Stop" onClick={() => command('/api/queue/stop')}/><Button label="Clear Automation Queue" onClick={() => command('/api/queue/clear')} disabled={!jobs.length}/></div>
    <input ref={csvInputRef} type="file" accept=".csv,text/csv" aria-label="Import automation CSV" className="hidden" onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void importCsv(file); }}/>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-300">Playwright automation</p><h1 className="text-3xl font-semibold">Posting queue</h1><p className="text-sm text-slate-400">Browser: {status.browser.open ? 'open' : status.browser.profileExists ? 'profile saved' : 'not created'} · Mode: {settings.headless ? 'headless' : 'visible'} · Worker: {status.state}</p></div><div className="flex flex-wrap gap-2"><Button label={importing ? 'Importing CSV…' : 'Import CSV'} onClick={() => csvInputRef.current?.click()} disabled={importing}/><Button label="Queue Manual CSV" onClick={queueRows} disabled={!rows.length}/><Button label="Open Visible Browser / Login" onClick={() => command('/api/browser/login', { headless: settings.headless })} disabled={settings.headless || status.hosted}/></div></div>
    {error && <p className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100">{error}</p>}
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><Metric label="Total" value={jobs.length}/>{Object.entries(counts).map(([key, value]) => <Metric key={key} label={key} value={value}/>)}</div>
    <div className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:grid-cols-3"><Field label="Delay between jobs (seconds)" value={settings.delayMs / 1000} onChange={(value) => setSettings({ ...settings, delayMs: value * 1000 })}/><Field label="Cooldown (seconds)" value={settings.cooldownMs / 1000} onChange={(value) => setSettings({ ...settings, cooldownMs: value * 1000 })}/><Field label="Maximum jobs" value={settings.maxJobs} onChange={(value) => setSettings({ ...settings, maxJobs: value })}/><Field label="Composer timeout (seconds, 1–120)" value={settings.composerTimeoutMs / 1000} onChange={(value) => setSettings({ ...settings, composerTimeoutMs: value * 1000 })}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.joinBeforePost} onChange={(event) => setSettings({ ...settings, joinBeforePost: event.target.checked })}/> Join group before posting</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.stopOnFailure} onChange={(event) => setSettings({ ...settings, stopOnFailure: event.target.checked })}/> Stop on failure</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.stopOnCheckpoint} onChange={(event) => setSettings({ ...settings, stopOnCheckpoint: event.target.checked })}/> Stop on security checkpoint</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.headless} disabled={status.browser.open || status.hosted} onChange={(event) => setSettings({ ...settings, headless: event.target.checked })}/> Run browser headless</label></div>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.copyClipboard} onChange={event => setSettings({ ...settings, copyClipboard: event.target.checked })}/> Also copy post text to the Windows clipboard (optional)</label>
    <div className="space-y-3 rounded-2xl border border-slate-800 p-4"><label className="block text-sm">Automatic membership answers<textarea value={membershipText} onChange={event => setMembershipText(event.target.value)} placeholder={'Why do you want to join = Your reason here\nWhere do you live = Your location here'} className="mt-2 min-h-28 w-full rounded-lg border border-slate-700 bg-slate-950 p-3"/></label><p className="text-xs text-slate-400">One question phrase = answer per line. Matches ignore capitalization and prefer the longest matching phrase. For multiple choice, use the exact option text. Answers stay in this browser; unknown questions require follow-up.</p><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.acceptGroupRules} onChange={event => setSettings({ ...settings, acceptGroupRules: event.target.checked })}/> Automatically agree to group rules when joining</label></div>
    {status.hosted && <p className="rounded-xl bg-amber-500/10 p-3 text-sm text-amber-100">Hosted Render mode requires headless operation. Use the local PasteHappy app for interactive Facebook login. Server queue and session data can be lost on redeployment or restart.</p>}
    <p className="text-xs text-slate-400">Headless mode runs without a visible browser window. Use visible mode for the first Facebook login and checkpoints; close an open Playwright browser before switching modes.</p>
    <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="p-2">Group</th><th className="p-2">Post preview</th><th className="p-2">Status</th><th className="p-2">Attempts</th><th className="p-2">Last error</th><th className="p-2">Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-t border-slate-800"><td className="p-2 font-medium">{job.groupName}</td><td className="max-w-xs truncate p-2">{job.postText}</td><td className="p-2">{job.status}</td><td className="p-2">{job.attempts}</td><td className="max-w-xs truncate p-2 text-rose-300" title={job.lastError || ''}>{job.lastError || '—'}</td><td className="p-2"><div className="flex gap-2"><a href={job.groupUrl} target="_blank" rel="noreferrer">Open Group</a>{['failed','blocked','uncertain','skipped'].includes(job.status) && <button className="text-sky-300" onClick={() => command(`/api/queue/${job.id}/retry`)}>Retry</button>}{!['posted','skipped'].includes(job.status) && <button className="text-amber-300" onClick={() => command(`/api/queue/${job.id}/skip`)}>Skip</button>}</div></td></tr>)}</tbody></table>{!jobs.length && <p className="p-4 text-sm text-slate-400">Import a CSV here or queue rows from the manual window to begin.</p>}</div>
    <p className="text-xs text-slate-400">Missing composers automatically skip after the configured timeout. Membership questions use your saved answers. Pending approval and unmatched questions are skipped for follow-up.</p>

  </section>;
}
async function api(path: string, init?: RequestInit) { const response = await fetch(path, init); const data = await response.json(); if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); return data; }
function Button({ label, onClick, disabled }: { label: string; onClick: () => void; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className="min-h-11 rounded-full border border-violet-400/50 bg-violet-500/20 px-4 text-sm font-semibold text-violet-50 disabled:cursor-not-allowed disabled:opacity-40">{label}</button>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-900 p-3"><p className="text-xs capitalize text-slate-400">{label}</p><p className="text-xl font-bold">{value}</p></div>; }
function Field({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-slate-400">{label}<input type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-white"/></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-700 bg-slate-950/60 p-3"><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 font-semibold text-white">{value}</dd></div>; }
